### ISSUE TITLE
More incorrect answers and correct answers

### ISSUE THREAD

**Issue by Araveous** [Gloryness/tassomai-automation#31]
It might just be my computer but this issue has just started today, I am getting a lot more answers incorrect than before, usually, I get like 31 correct and 5 wrong but now it's like it's swapped around. Help, please.

**Comment by Eno-Gerguri** [comment]
It's because the size of the database has reached its one file limit to be downloaded over the GitHub API, which is being used.

The owner stopped the database from growing in order to make it still work.

This means that it is no longer storing new correct answers and not growing its database to be bigger.

You keep getting new questions, which the bot hasn't seen and the bot is not storing the correct answer. Hence why you are getting so many wrong.

Solution: Going to have to wait for a patch, which organises the answers into a way that can be used in a smaller file size in order to keep it working correctly.

**Comment by Araveous** [comment]
Ok, I'll wait, thanks.
