### ISSUE TITLE
Possible Work around for tassomai detecting bots?

### ISSUE THREAD

**Issue by BIGboyal** [Gloryness/tassomai-automation#59]
I don't know if you would actually be able to do this but, you could make a program that looks at tassomai on your browser, starts a quiz, looks up the answers for the quiz, refreshes the page, matches a correct answer to the question and auto-clicks it, so it looks like it was user input. again I don't know if this will be able to be done but it should be undetectable. thanks @Gloryness

**Comment by Gloryness** [comment]
This is browser automation, something that is easily done using Selenium. I've tried this before but it can detect selenium so that will not work. plus selenium takes ages to load. Without selenium though, this would be fine but there is no way to actually automate the current browser your on without selenium.

But this is kind of similar to the Lookup tab I've added in the new update. It does the exact same thing you're describing here but just looks up the answers and unpacks it for you to view. Instead of it automatically answering the questions, you have to manually do the quiz yourself - all it just is just provides you with the answers (sometime it isn't 100% accurate but this is where the "Question" mode comes in as described in the update).

**Comment by BIGboyal** [comment]
Hi, not sure weather this would help or work with your code but I found this https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by Gloryness** [comment]
This is pretty cool but as I said it's pretty slow and will require quite a bit of time to implement this. And each question/answer is retrieved through the API so it's raw and untouched which is perfect however if I were to automate it with selenium I would have to literally scrape it from the webpage source code and the text could contain symbols (which are called mathjax) which is just way too confusing to turn it into RAW text.

So I'll prefer to not use Selenium - it would be easier to try and find a solution to progress wiped instead of a complex workaround

**Comment by Gloryness** [comment]
> 
> 
> @Gloryness Hi, I'm working on my own undetected tassomai bot which works so far. Could you tell me how you got the question answers for your program, I've looked in the source code but haven't been able to locate how you get the answers. thanks

Does it work with the API or via selenium? and the answers are stored in a private github. I can walk you through on how to get them if you want just contact me on disc gloryy#1342

**Comment by BIGboyal** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver it uses this which is a selenium patch so it has all the same syntax. i sent you a discord friend request my username is alex1
