### ISSUE TITLE
Cmd commands won't work

### ISSUE THREAD

**Issue by IamNotARobot1** [Gloryness/tassomai-automation#8]
I'm trying to create a .cmd file to automatically start the program, but the --start command and others won't work. The tassomai automation program pops up for less than a second, then disappears.
![tassomai auto error 1](https://user-images.githubusercontent.com/77235742/104125309-c48b9000-534d-11eb-88d5-40d46ca99e2e.PNG)
Because one of the errors was that there was "no such file as temp.json", I renamed the answers.json to temp.json to see what would happen, and it started working. When I tried again, "no such file as temp.json" came up again, and when I checked the tassomai-automation file in local appdata again, the file I had renamed temp.json had renamed itself back to answers.json.
Also, could there be an option for the program to get a few questions wrong because 100% accuracy rate looks quite suspicious.
I have no experience in programming or coding, so I'm sorry if I'm being stupid.

**Comment by Gloryness** [comment]
I think the options arent working because your putting quotes around them. And also try running it from the folder the executable is located in and btw renaming answers.json to temp.json wont solve the problem, temp.json is only used to collect the private database and then it deletes the file after its done collecting it.

try doing this without the quotes around the options:
```cmd
"Tassomai Automation.exe" --start --delay=question --daily
```
